<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_PneuCyl_1Pos" Id="{a7b52489-8306-4768-bce5-7bb6030c1e74}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_PneuCyl_1Pos EXTENDS FB_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="01 Properties" Id="{c888f04d-257a-4261-96a3-2bc2ced9cf8a}" />
    <Folder Name="02 Methodes" Id="{a74a2467-4e6f-4a46-b8d2-e35efb4de658}" />
    <Property Name="Busy" Id="{e580c84e-b274-4f1c-9942-605e02480dcb}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0bdc067b-203b-4007-b07f-9fbbc24101e1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{74170e3a-f218-473d-879b-b312250d3d8d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Done" Id="{843e882c-3ac9-405b-b0b9-910d7a537772}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{f87b0759-5c4c-4f3c-bbb8-43573a8ec162}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{57f52870-a917-4d54-8f72-4b9f627bcb85}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Enable" Id="{050e17ca-282c-4e06-b630-7667ffc73d78}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Enable : BOOL
]]></Declaration>
      <Get Name="Get" Id="{27d89eaf-1591-41f2-bc3b-6f43f759e320}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{77de8c84-c0ab-4551-9c0d-5f01fa0b15c9}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Error" Id="{cab2b3b0-4833-4a26-9b3a-875db2d4109d}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{2479d3f4-286a-4bbc-b76c-6d181eaa3d75}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{37b4aa2a-d320-4c61-b7fd-0e9af1a32822}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="FB_Init" Id="{34a01689-1654-4ffa-b208-161dc9b86395}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[//FB_Init ist immer implizit verfügbar und wird primär für die Initialisierung verwendet.
//Der Rückgabewert wird nicht ausgewertet. Für gezielte Einflussnahme können Sie
//die Methoden explizit deklarieren und darin mit dem Standard-Initialisierungscode 
//zusätzlichen Code bereitstellen. Sie können den Rückgabewert auswerten.
METHOD FB_Init: BOOL
VAR_INPUT    
	bInitRetains					: BOOL; 					// TRUE: Die Retain-Variablen werden initialisiert (Reset warm / Reset kalt)    
	bInCopyCode						: BOOL;  					// TRUE: Die Instanz wird danach in den Kopiercode kopiert (Online-Change)
	
	I_Name                : STRING;         //  Name
	I_ID                  : UINT;            // ID
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
    <Property Name="ID" Id="{48421c43-54ec-4272-8829-102bb54c8894}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY ID : UINT
]]></Declaration>
      <Get Name="Get" Id="{99aef2e9-0e2c-4169-8cac-4c38178b3fbb}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{41b850d8-6142-4622-990b-21a4e54bf64b}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="mEnable" Id="{a837f753-93ae-4f1c-8c43-13d31a0e418c}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[{error 'Methodenimplementierung hinzufügen oder Methode löschen, um die Basisimplementierung zu verwenden'}
METHOD mEnable : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="mInit" Id="{e5d1dcd0-82ba-457b-a512-ca925612ad74}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[{error 'Methodenimplementierung hinzufügen oder Methode löschen, um die Basisimplementierung zu verwenden'}
METHOD mInit : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Mode" Id="{967c651f-5ff2-4570-8307-b32955360277}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Mode : E_Mode
]]></Declaration>
      <Get Name="Get" Id="{e33cb558-dced-42b5-83a7-156b180e5cbf}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{dabef150-037d-4592-b8f5-4e11fbcefdab}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="mReset" Id="{bc3e8d40-9767-4b8c-b096-08af42010a51}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[{error 'Methodenimplementierung hinzufügen oder Methode löschen, um die Basisimplementierung zu verwenden'}
METHOD mReset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Name" Id="{73f577ad-4be0-4fe0-9dba-b0591e6ffebc}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Name : STRING
]]></Declaration>
      <Get Name="Get" Id="{3fc94e22-2d91-4b44-b472-95d70d549c73}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{c40b8545-966f-429c-92a4-65f9bbd5a20f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>