<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_ReadHead" Id="{7b3aad50-65da-4b94-b70d-8f823da603e1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ReadHead EXTENDS FB_Base
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="01 Properties" Id="{b2440afa-7c1f-40b4-9cbc-93b18aee1299}" />
    <Folder Name="02 Methodes" Id="{ffaef3c6-238b-4512-a039-09cfff86c625}" />
    <Property Name="Busy" Id="{8e2d95da-2d16-44f1-921e-4c5f2fa2aa67}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{ed19278a-dd2d-47ad-b866-b771f582d9c0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{92cd5884-e2a0-4538-970a-096fbaa3cea7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Done" Id="{41f964d9-1435-488c-a7bd-1ddfed8a7300}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{605b882e-703f-4b99-9d29-d73625145c96}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{6e5e2bad-d04e-4363-b2ca-45b1ba54d77c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Enable" Id="{d5f8fb91-7519-4820-b972-23d532c8183c}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Enable : BOOL
]]></Declaration>
      <Get Name="Get" Id="{58d53687-cf44-4f8f-bd13-0872cf25d035}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{05a828ed-896a-4d50-9e7f-b6fb70c9f189}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Property Name="Error" Id="{3dace300-9451-4aee-9586-206813d15ed9}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{76f7c0e2-6ef0-498e-a20f-21c89357254c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{be03cd2f-a471-485a-98bb-0717928138ec}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="FB_Init" Id="{e8a7e786-1a56-4f8b-9239-87a55b695227}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[//FB_Init ist immer implizit verfügbar und wird primär für die Initialisierung verwendet.
//Der Rückgabewert wird nicht ausgewertet. Für gezielte Einflussnahme können Sie
//die Methoden explizit deklarieren und darin mit dem Standard-Initialisierungscode 
//zusätzlichen Code bereitstellen. Sie können den Rückgabewert auswerten.
METHOD FB_Init: BOOL
VAR_INPUT    
	bInitRetains					: BOOL; 					// TRUE: Die Retain-Variablen werden initialisiert (Reset warm / Reset kalt)    
	bInCopyCode						: BOOL;  					// TRUE: Die Instanz wird danach in den Kopiercode kopiert (Online-Change)
	
	I_Name                : STRING;         //  Name
	I_ID                  : UINT;            // ID
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
    <Property Name="ID" Id="{fb3c7a37-8e2c-4628-9e53-b408ad97fbcc}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY ID : UINT
]]></Declaration>
      <Get Name="Get" Id="{1ee644ae-5c6a-4aa1-b356-a92d554c43a6}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{66be638b-73bb-46a0-b0dc-09ac6a9dfccf}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="mEnable" Id="{6d414898-f569-411f-b415-9b2add5e63fc}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[{error 'Methodenimplementierung hinzufügen oder Methode löschen, um die Basisimplementierung zu verwenden'}
METHOD mEnable : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="mInit" Id="{b59169e6-0a59-4156-b19f-b27e54bd2168}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[{error 'Methodenimplementierung hinzufügen oder Methode löschen, um die Basisimplementierung zu verwenden'}
METHOD mInit : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Mode" Id="{0035497a-1335-46df-bfd9-1c9406389bf1}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Mode : E_Mode
]]></Declaration>
      <Get Name="Get" Id="{21eae457-0aea-4bac-831a-609374875631}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{6c2aac49-6ef3-471c-9d5d-24014ba55501}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
    <Method Name="mReset" Id="{7950ae76-25a0-4407-96d2-d54e03fe6333}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[{error 'Methodenimplementierung hinzufügen oder Methode löschen, um die Basisimplementierung zu verwenden'}
METHOD mReset : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Name" Id="{f8dcdae6-86fa-42cc-bc58-d7bdf93f60bd}" FolderPath="01 Properties\">
      <Declaration><![CDATA[{error 'Eigenschaftenimplementierung hinzufügen oder Eigenschaft löschen, um die Basisimplementierung zu verwenden'}
PROPERTY Name : STRING
]]></Declaration>
      <Get Name="Get" Id="{cce02a08-f8ae-4189-a72c-72713f7e0d82}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
      <Set Name="Set" Id="{cb9daad1-607b-48f0-84b9-084508e1e8bd}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Set>
    </Property>
  </POU>
</TcPlcObject>