<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_Input" Id="{03a6797d-89e6-4bde-a671-dac2f9ab8585}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Input EXTENDS FB_Base
VAR_INPUT
	bBoolValue												: BOOL; 
END_VAR

VAR
	bIAT_bHardwareLink	AT %I*				:	BOOL; // hardware link
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[SUPER^();

bBoolValue := bIAT_bHardwareLink;
]]></ST>
    </Implementation>
    <Folder Name="01 Properties" Id="{dd12400f-aed7-4dfb-b4cb-d45c40bffe5f}" />
    <Folder Name="02 Methodes" Id="{ddadb740-76eb-481d-b099-2fbd7a9a1f63}" />
    <Method Name="FB_Init" Id="{4e017715-16ee-49cc-b11c-5f9f51604256}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[//FB_Init ist immer implizit verfügbar und wird primär für die Initialisierung verwendet.
//Der Rückgabewert wird nicht ausgewertet. Für gezielte Einflussnahme können Sie
//die Methoden explizit deklarieren und darin mit dem Standard-Initialisierungscode 
//zusätzlichen Code bereitstellen. Sie können den Rückgabewert auswerten.
METHOD FB_Init: BOOL
VAR_INPUT    
	bInitRetains					: BOOL; 					// TRUE: Die Retain-Variablen werden initialisiert (Reset warm / Reset kalt)    
	bInCopyCode						: BOOL;  					// TRUE: Die Instanz wird danach in den Kopiercode kopiert (Online-Change)
	
	I_Name                : STRING;         //  Name
	I_ID                  : UINT;            // ID
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>