<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4026.18">
  <POU Name="FB_Output" Id="{715a29c0-eb36-402b-9452-917ebd499c43}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Output EXTENDS FB_Base
VAR_INPUT
	bBoolValue								: BOOL;
END_VAR
VAR_OUTPUT
	
END_VAR
VAR
	bQAT_HardwareLink	AT %Q*	:	BOOL; // hardware link
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
SUPER^();

bQAT_HardwareLink := bBoolValue;]]></ST>
    </Implementation>
    <Folder Name="01 Properties" Id="{9d6af48d-62fd-4d0e-81de-2d1da5d95d10}" />
    <Folder Name="02 Methodes" Id="{ba7fe19f-05fa-4d1d-aa9b-55739006f574}" />
    <Method Name="FB_Init" Id="{9d459484-0a98-4dfa-8694-3a768efa9913}" FolderPath="02 Methodes\">
      <Declaration><![CDATA[//FB_Init ist immer implizit verfügbar und wird primär für die Initialisierung verwendet.
//Der Rückgabewert wird nicht ausgewertet. Für gezielte Einflussnahme können Sie
//die Methoden explizit deklarieren und darin mit dem Standard-Initialisierungscode 
//zusätzlichen Code bereitstellen. Sie können den Rückgabewert auswerten.
METHOD FB_Init: BOOL
VAR_INPUT    
	bInitRetains					: BOOL; 					// TRUE: Die Retain-Variablen werden initialisiert (Reset warm / Reset kalt)    
	bInCopyCode						: BOOL;  					// TRUE: Die Instanz wird danach in den Kopiercode kopiert (Online-Change)
	
	I_Name                : STRING;         //  Name
	I_ID                  : UINT;            // ID
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>